#!/usr/bin/env bash
# Tells a story of passwd
while IFS=: read -r username password user_id group_id userinfo home shell; do
	echo "The user $username is part of the $group_id gang," \
	"lives in $home and rides $shell." \
	"$user_id's place is protected by the passcode $password," \
	"more info about the user here: $userinfo"
done < /etc/passwd
